name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.26.0
    - run: deno task fmt
    - run: deno task coverage
    - uses: codecov/codecov-action@v2
      with:
        files: ./cov_profile.lcov
        fail_ci_if_error: true
