name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.14.0
    - run: deno install -qAn vr https://deno.land/x/velociraptor@1.2.0/cli.ts
    - run: vr fmt
    - run: vr coverage
    - uses: codecov/codecov-action@v2
      with:
        files: ./cov_profile.lcov
        fail_ci_if_error: true
